name: rctms
description: Realtime Collaborative Task Management System
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Setting a compatible SDK range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State management
  flutter_riverpod: ^2.3.6
  # API
  graphql_flutter: ^5.1.2
  http: ^1.1.0
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  # UI and widgets
  fl_chart: ^0.63.0
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  # Connectivity
  connectivity_plus: ^4.0.2
  # Utils
  path_provider: ^2.1.1
  uuid: ^3.0.7
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true