// lib/data/models/comment_model.dart
import 'package:json_annotation/json_annotation.dart';
import 'package:rctms/app/domain/entities/comment.dart';
part 'comment_model.g.dart';  // Will be generated by build_runner

@JsonSerializable()
class CommentModel extends Comment {
  CommentModel({
    required String id,
    required String content,
    required String taskId,
    required String userId,
    required DateTime createdAt,
    required DateTime updatedAt,
  }) : super(
          id: id,
          content: content,
          taskId: taskId,
          userId: userId,
          createdAt: createdAt,
          updatedAt: updatedAt,
        );
  
  factory CommentModel.fromJson(Map<String, dynamic> json) => 
      _$CommentModelFromJson(json);
  
  Map<String, dynamic> toJson() => _$CommentModelToJson(this);
  
  factory CommentModel.fromEntity(Comment comment) => CommentModel(
        id: comment.id,
        content: comment.content,
        taskId: comment.taskId,
        userId: comment.userId,
        createdAt: comment.createdAt,
        updatedAt: comment.updatedAt,
      );
}