// lib/data/models/project_model.dart
import 'package:json_annotation/json_annotation.dart';
import 'package:rctms/app/domain/entities/project.dart';

part 'project_model.g.dart';  // Will be generated by build_runner

@JsonSerializable()
class ProjectModel extends Project {
  ProjectModel({
    required String id,
    required String name,
    String? description,
    required String ownerId,
    required DateTime createdAt,
    required DateTime updatedAt,
  }) : super(
          id: id,
          name: name,
          description: description,
          ownerId: ownerId,
          createdAt: createdAt,
          updatedAt: updatedAt,
        );
  
  factory ProjectModel.fromJson(Map<String, dynamic> json) => 
      _$ProjectModelFromJson(json);
  
  Map<String, dynamic> toJson() => _$ProjectModelToJson(this);
  
  factory ProjectModel.fromEntity(Project project) => ProjectModel(
        id: project.id,
        name: project.name,
        description: project.description,
        ownerId: project.ownerId,
        createdAt: project.createdAt,
        updatedAt: project.updatedAt,
      );
}