// lib/data/models/task_model.dart
import 'package:json_annotation/json_annotation.dart';
import 'package:rctms/app/domain/entities/task.dart';

part 'task_model.g.dart';  // Will be generated by build_runner

@JsonSerializable()
class TaskModel extends Task {
  TaskModel({
    required String id,
    required String title,
    String? description,
    required TaskStatus status,
    required TaskPriority priority,
    DateTime? dueDate,
    required String projectId,
    String? assigneeId,
    required String creatorId,
    required DateTime createdAt,
    required DateTime updatedAt,
  }) : super(
          id: id,
          title: title,
          description: description,
          status: status,
          priority: priority,
          dueDate: dueDate,
          projectId: projectId,
          assigneeId: assigneeId,
          creatorId: creatorId,
          createdAt: createdAt,
          updatedAt: updatedAt,
        );
  
  factory TaskModel.fromJson(Map<String, dynamic> json) => 
      _$TaskModelFromJson(json);
  
  Map<String, dynamic> toJson() => _$TaskModelToJson(this);
  
  factory TaskModel.fromEntity(Task task) => TaskModel(
        id: task.id,
        title: task.title,
        description: task.description,
        status: task.status,
        priority: task.priority,
        dueDate: task.dueDate,
        projectId: task.projectId,
        assigneeId: task.assigneeId,
        creatorId: task.creatorId,
        createdAt: task.createdAt,
        updatedAt: task.updatedAt,
      );
}