// lib/data/models/user_model.dart
import 'package:json_annotation/json_annotation.dart';
import 'package:rctms/app/domain/entities/user.dart';

part 'user_model.g.dart';  // Will be generated by build_runner

@JsonSerializable()
class UserModel extends User {
  UserModel({
    required String id,
    required String email,
    required String username,
    required DateTime createdAt,
    required DateTime updatedAt,
  }) : super(
          id: id,
          email: email,
          username: username,
          createdAt: createdAt,
          updatedAt: updatedAt,
        );
  
  factory UserModel.fromJson(Map<String, dynamic> json) => 
      _$UserModelFromJson(json);
  
  Map<String, dynamic> toJson() => _$UserModelToJson(this);
  
  factory UserModel.fromEntity(User user) => UserModel(
        id: user.id,
        email: user.email,
        username: user.username,
        createdAt: user.createdAt,
        updatedAt: user.updatedAt,
      );
}